export const textFieldWrapper: string;
export const textFieldLabelWrapper: string;
export const textField: string;
export const textFieldContent: string;
export const textFieldContentFocus: string;
export const textFieldLabel: string;
export const textFieldContentError: string;
export const textFieldLabelWrapperFull: string;
export const textFieldLabelDisabled: string;