export const row: string
export const col: string
export const col1: string
export const col2: string
export const col3: string
export const col4: string
export const col5: string
export const col6: string
export const col7: string
export const col8: string
export const col9: string
export const col10: string
export const col11: string
export const col12: string
export const col13: string
export const col14: string
export const col15: string
export const col16: string
export const col17: string
export const col18: string
export const col19: string
export const col20: string
export const col21: string
export const col22: string
export const col23: string
export const col24: string